products/urls.py
from django.urls import path
from .views import SearchView,\
    ResultView,\
    ProductDetail,\
    MyProductView,\
    substitute,\
    ErrorView

app_name = 'products'

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('sentry-debug/', trigger_error),
    path('results/<int:pk>', ResultView.as_view(), name='results'),
    path('search/', SearchView.as_view(), name="search"),
    path('<int:pk>/details/', ProductDetail.as_view(), name='details'),
    path('myproducts/', MyProductView.as_view(), name='myproducts'),
    path('substitute/<int:product_id>/<int:substitute_id>',
         substitute,
         name='substitute'
         ),
    path('alreadySaved/', ErrorView.as_view(), name='errors'),
]

purBeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('products/', include('products.urls')),
    path('legal/', TemplateView.as_view(template_name='legal_mention.html'), name='legal'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

users/urls.py
from django.urls import path
from .views import SignUpView, AccountView
from django.contrib.auth import views


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('account/', AccountView.as_view(), name='account'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

products/models.py
from django.db import models
from purBeurre.settings import AUTH_USER_MODEL


class Category(models.Model):
    """ Categories table """
    category_name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.category_name


class Product(models.Model):
    """ Models for all  the products """
    product_name = models.CharField(max_length=255)
    nutrition_grades = models.CharField(max_length=2)
    fat = models.CharField(max_length=30)
    fat_100g = models.DecimalField(max_digits=3, decimal_places=1)
    saturated_fat = models.CharField(max_length=30)
    saturated_fat_100g = models.DecimalField(max_digits=3, decimal_places=1)
    sugars = models.CharField(max_length=30)
    sugars_100g = models.DecimalField(max_digits=3, decimal_places=1)
    salt = models.CharField(max_length=30)
    salt_100g = models.DecimalField(max_digits=30, decimal_places=1)
    image_url = models.URLField()
    url = models.URLField()

    categories = models.ManyToManyField(Category, related_name="products")

    def __str__(self):
        return self.product_name


class Favorite(models.Model):
    """ Table where the user's favorite products will be saved """
    product = models.ForeignKey(
        Product,
        related_name='product',
        on_delete=models.CASCADE
    )
    substitute = models.ForeignKey(
        Product,
        related_name='substitute',
        on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.CASCADE
    )

    class Meta:
        """ Class to forbid duplicate product """
        unique_together = (('product_id', 'substitute_id', 'user_id'),)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

from django.utils import timezone

from .managers import CustomUserManager


class UserProfile(AbstractBaseUser, PermissionsMixin):
    """ Models where we saved all the user's information"""
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField('email address', unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
# from django import forms
from django.contrib.auth.forms import UserChangeForm, \
    UserCreationForm
from .models import UserProfile


class SignupForm(UserCreationForm):
    """
        Forms to create a user, with no privileges,
        from the given email and password
    """

    class Meta:
        model = UserProfile
        fields = (
            'last_name',
            'first_name',
            'email',
            )


class SignupChange(UserChangeForm):
    """Forms to make update later in the user's account"""
    class Meta:
        model = UserProfile
        fields = (
            'last_name',
            'first_name',
            'email',
        )

products/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Q, Count
from django.shortcuts import get_object_or_404, redirect
from .models import Product, Favorite


class SearchView(ListView):
    """ Return the search input and send the request to our db."""
    model = Product
    template_name = 'products/search_products.html'
    paginate_by = 9

    def get_queryset(self):
        product_query = self.request.GET.get("product_search")
        return Product.objects\
            .filter(Q(product_name__icontains=product_query) |
                    Q(categories__category_name__icontains=product_query))\
            .distinct()\
            .order_by('product_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.request.GET.get("product_search")
        return context


class ResultView(ListView):
    """
        Return substitutes with same category but better or at list
        same nutrition grades.
    """
    context_object_name = "products_list"
    template_name = 'products/results.html'
    paginate_by = 6

    def get_queryset(self, common_cat=3):
        self.product = get_object_or_404(Product, pk=self.kwargs['pk'])
        cat = self.product.categories.all()
        return Product.objects\
            .filter(categories__in=cat,
                    nutrition_grades__lte=self.product.nutrition_grades)\
            .annotate(similar=Count('categories'))\
            .filter(similar__gte=common_cat)\
            .order_by('nutrition_grades')[:9]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = self.product.categories
        context['product'] = self.product
        context['image'] = self.product.image_url
        return context


class ProductDetail(DetailView):
    """"return the substitute's details"""
    model = Product
    template_name = 'products/details.html'
    context_object_name = 'substitute'


class MyProductView(LoginRequiredMixin, ListView):
    """ Class that allow the display of the user's saved products"""
    template_name = 'products/my_products.html'
    paginate_by = 6

    def get_queryset(self):
        return Favorite.objects.filter(
            user_id=self.request.user.id
        ).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Mes produits favoris"
        return context


class ErrorView(ListView):
    """ To show error's message if product already saved"""
    model = Favorite
    template_name = "products/alreadySaved.html"


@login_required
def substitute(request, product_id, substitute_id):
    """ Function to save sustitute product in the favorite's table"""
    try:
        Favorite.objects.create(
            product_id=product_id,
            substitute_id=substitute_id,
            user_id=request.user.id
        )
        return redirect('products:myproducts')
    except IntegrityError:
        return redirect('products:errors')

users/views.py
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy

from .forms import SignupForm


class SignUpView(CreateView):
    """ class to display the signup's page"""
    form_class = SignupForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'


class AccountView(LoginRequiredMixin, CreateView):
    template_name = 'users/account.html'

    def get(self, request, *args, **kwargs):
        fullname = ' '.join([request.user.first_name, request.user.last_name])
        context = {'fullname': fullname}
        return render(request, self.template_name, context)

products/templates/products/alreadySaved.html
{% extends '_base.html' %}
{% block content %}
    <section id="errors" class="flex-grow-1">
        <div class="container height-container main">
          <div class="row align-items-center justify-content-center py-3">
            <h2>Produit déjà enregistré</h2>
          </div>
        </div>
    </section>
    {% include 'footer.html' %}
{% endblock %}

products/templates/products/details.html
{% extends '_base.html' %}

{% load static %}

{% block content %}
    <header id="product-search" class="substitute-image">
        <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <h1 class="text-white font-weight-bold mb-5">{{ substitute.product_name }}</h1>
            </div>
        </div>
    </header>

    <!-- Product Detail -->
<section id="product-details">
    <div class="container mt-5">
            <div class="row align-items-center justify-content-center mt-5">
                <div class="col-12 col-lg-6 mt-5">
                    <img src="{% static 'src/assets/img/nutricode/nutriscore-'|add:substitute.nutrition_grades|add:'.svg' %}" alt="{{ substitute.product_name }}">
                </div>
                <div class="nutri-quality mt-5">
                    <h3>Repère nutritionnel pour 100g</h3>
                    <ul class="food-level list-group list-group-flush mt-5">
                        <li class="fat list-group-item">Lipide: {{ substitute.fat_100g }}g </li>
                        <li class="saturated_fat list-group-item">Graisse saturée: {{ substitute.saturated_fat_100g }}g</li>
                        <li class="sugar list-group-item">Glucide: {{ substitute.sugars_100g }}g</li>
                        <li class="salt list-group-item">Sel: {{ substitute.salt_100g }}g</li>
                    </ul>
                </div>
                <div class="button mt-5 mb-5 align-items-center justify-content-center">
                    <div class="link mr-5">
                        <a href="{{ substitute.url }}">
                            <button type="button" class="btn btn-lg btn-outline-info">
                                Voir la fiche d'OpenFoodFacts
                            </button>
                        </a>
                    </div>
                    <div class="back ml-5">
                        <button class="btn btn-lg btn-outline-secondary" onclick="window.history.back()" type="button">
                            Retour
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    {% include 'footer.html' %}

<style>
    .substitute-image {
        height: 350px;
        padding-top: 10rem;
        background-color: #345A61;
        background: linear-gradient(to bottom,rgba(92,77,66,.8) 0,rgba(92,77,66,.8) 100%),
            url({{substitute.image_url}});
        background-repeat: repeat;
        background-position-x: 35%;
        background-position-y: 50%;
        }
</style>

{% endblock content %}

products/templates/products/my_products.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
    {% include '_base_title.html' %}
    <div class="my_products container main flex-grow-1">
        <div class="row mt-5 justify-content-center align-items-center">
            {% if not object_list %}
                <div class="row align-items-center justify-content-center mb-5">
                    <div class="alert alert-warning mt-5"> Aucun produit enregistré</div>
                </div>
            {% endif %}
            {% for product in object_list %}
                <div class="row align-items-center justify-content-center">
                    <div class="col-11 col-lg-4 product-image">
                        <div class="product-thumb-myproduct">
                            <div class="nutriscore text-right">{{ product.product.nutrition_grades|upper }}
                                <a href="{% url 'products:details' product.product.id %}">
                                    <img src="{{ product.product.image_url }}" class="shadow-sm p-3 mb-5 bg-white card-img rounded mx-auto d-block" alt="">
                                </a>
                                <div class="product-thumb-legend mb-5">
                                    <div class="product_name text-center">
                                        {{ product.product.product_name }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="new-arrow">
                      <button class="arrow -long -huge -roobios"><span class="visually-hidden"></span></button>
                    </div>
                    <div class="col-11 col-lg-4 product-image">
                        <div class="product-thumb-myproduct">
                            <div class="nutriscore text-right">{{ product.substitute.nutrition_grades|upper }}
                                <a href="{% url 'products:details' product.substitute.id %}">
                                    <img src="{{ product.substitute.image_url }}" class="shadow-sm p-3 mb-5 bg-white card-img rounded mx-auto d-block" alt="">
                                </a>
                                <div class="product-thumb-legend mb-5">
                                    <div class="product_name text-center">
                                        {{ product.substitute.product_name }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">Précédente</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">Suivante</a>
                      {% endif %}
                  </span>
              </div>
            {% endif %}
        </div>
    </div>
    {% include 'footer.html' %}
{% endblock %}

products/templates/products/results.html
{% extends '_base.html' %}

{% load static %}

{% block content %}
     <header id="product-search" class="bg-product-search mb-5">
        <div class="container-fluid h-200">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="text-center mb-5">
                    <h2 class="text-white font-weight-bold mb-4">{{ product.product_name }}</h2>
                    <img class="card-img rounded mx-auto d-block" src="{{ product.image_url}}" alt="{{ product.product_name }}">
                </div>
            </div>
        </div>
    </header>
    <div class="container main flex-grow-1">
        <div class='row align-items-center justify-content-center'>
            <div class="col-12 text-center mt-3 mb-5">
                <h2>Vous pouvez remplacer cet aliment par:</h2>
            </div>
             {% if not products_list %}
                 <div class="alert alert-warning"> {{ title|title }} indisponible</div>
            {% endif %}
            {% for sub in products_list %}
                <div class="col-11 col-lg-4 product-image">
                    <div class="product-thumb mb-5 mt-3">
                        <div class="nutri-grade text-right ">{{ sub.nutrition_grades|upper }}
                            <a href="{%  url 'products:details' sub.id %}">
                                <img src="{{ sub.image_url}}" class="shadow-sm p-3 mb-3 bg-white card-img rounded mx-auto d-block" alt="product image">
                            </a>
                            <div class="product-thumb-legend mb-5">
                                <div class="text-center">{{sub|title}}</div>
                                <div class="text-center">
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'products:substitute' product_id=product.id substitute_id=sub.id %}">
                                            <button type="submit" class="btn btn-link"><i class="fas fa-save"></i> Sauvegarder</button>
                                        </a>
                                    {% else %}
                                        <a href="{% url 'login' %}">
                                            Se connecter pour sauvegarder
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
    {% include 'footer.html' %}
{% endblock content %}

products/templates/products/search_products.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
    {% include '_base_title.html' %}
<div class="container main flex-grow-1">
    <div class="row product-search">
        <div class="col-12 text-center mt-2 mb-5">
            <h2>Choisissez le produit que vous souhaitez substituer</h2>
        </div>
        {% if not product_list %}
            <div class="alert alert-warning"> {{ title|title }} indisponible</div>
        {% endif %}
        {% for product in product_list %}
            <div class="col-11 col-lg-4 product-image">
                <div class="product-thumb mb-5">
                    <div class="nutri-grade text-right mt-5">{{ product.nutrition_grades|upper }}
                        <div class="text-center mt-4">
                            <a href="{%  url 'products:results' product.id %}" >
                                <img class="shadow-sm p-3 mb-3 bg-white rounded card-img mx-auto d-block" src="{{ product.image_url }}" alt="{{ product.product_name }}">
                                <div class="product_name text-center">{{ product.product_name }}</div>
                                <button class="btn btn-md btn-outline-secondary" type="button">Substituer</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if is_paginated %}
          <div class="pagination ">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">Précédente</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}" class="next-page ">Suivante</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
    </div>
</div>
    {% include 'footer.html' %}
{% endblock %}

templates/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'dist/assets/img/logo_pur_beurre-favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'dist/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top" class="d-flex flex-column min-vh-100">
        {% block nav %}
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'home' %}" class="navbar-brand js-scroll-trigger logo">
                            <img class="purbeurre-logo" src="{% static 'dist/assets/img/logo_pur_beurre.png' %}">
                            Pur Beurre
                        </a>
                    </div>
                </div>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Search form -->
                <div class="col-6 form-div">
                    <div class="col-5">
                        <form action="{% url 'products:search' %}">
                            <div class="form-group justify-content-center align-items-center">
                                <label for="search"></label>
                                <input id="search" class="form-control search" type="text" placeholder="Chercher" aria-label="Search" name="product_search">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <div class="col-14 connect-options">
                        <ul class="navbar-nav ml-auto my-2 my-lg-0">
                                {% if user.is_authenticated %}
                                    <p class="user-name"> Bonjour, {{user.first_name}} </p>
                                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account' %}"><i class="fas fa-user"></i></a></li>
                                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'products:myproducts' %}"><i class="fas fa-carrot"></i></a></li>
                                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
                                {% else %}
                                    <li class="nav-item connect"><a class="nav-link js-scroll-trigger" href="{% url 'login' %}">Connexion</a>
                                    <li class="nav-item sign-up"><a class="nav-link js-scroll-trigger" href="{% url 'signup' %}">Créer un compte</a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        {% endblock nav%}
        {% block content %}

        {% endblock content %}
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'dist/js/scripts.js' %}"></script>
    </body>
</html>

templates/_base_title.html
<header id="user-name" class="presentation bg-user-name bg-primary mb-5 mt-0">
    <div class="container-fluid">
      <div class="row align-items-center justify-content-center text-center">
        <h2 class="text-white font-weight-bold mb-5">{{ title|title }}</h2>
      </div>
    </div>
</header>

templates/footer.html
<footer class="py-3 bg-secondary footer" >
  <div class="container">
      <div class="row">
          <div class="text-center col-6">
              <a href="{% url 'legal' %}" class="text-dark">Mentions légales</a>
          </div>
          <div class="text-center col-6">Contact</div>
      </div>
    </div>
</footer>

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page PurBeurre{% endblock title %}
{% block content %}
    {% block header %}
        <header class="masthead presentation">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase font-weight-bold">Du gras oui mais de qualité!</h1>
                        <h2> Trouvez un produit de substitution pour ceux que vous consommez tous les jours </h2>
                    </div>
                    {% include 'search.html' %}
                </div>
            </div>
        </header>
    {% endblock header %}
        <!-- About-->
        <section class="page-section bg-light " id="about">
            <div class="container">
                 <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-dark mt-0">Colette et Remy</h2>
                        <hr class="divider my-4">
                        <h2 class="text-black mt-5">De la ratatouille aux croissants</h2>
                        <p class="text-black-50 mb-4 mt-4 phrase">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
                        <div class="row story">
                            <div class="col-lg-6 col-12 order-1">
                                <p class="text-black-50 mb-4 text-justify"><strong class="text-dark">Colette Tatou :</strong> "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
                                <img class="col-lg-6 col-12 order-lg-3 story-image" src="{% static 'src/assets/img/colette-tatou-full.png' %}" alt="colette image">
                            </div>
                            <div class=" col-lg-6 col-12 order-2">
                                <p class="text-black-50 mb-4 text-justify"><strong class="text-dark">Remy :</strong> "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
                                <img class="col-lg-6 col-12 order-lg-4 mt-4 story-image" src="{% static 'src/assets/img/ratatouille-portrait.jpg' %}" alt="remy image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Contactez-nous!</h2>
                        <hr class="divider my-4" />
                        <p class="mb-5">Vous souhaitez partager votre avoir du bon gras avec nous, n'hésitez pas!</p>
                    </div>
                </div>
                <div class="row contact">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3"></i>
                        <div class="phone">+1 (555) 123-4567</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3"></i>
                        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                        <a class="d-block mail" href="mailto:contact@yourwebsite.com">contact@yourwebsite.com</a>
                    </div>
                </div>
            </div>
        </section>
    {% include 'footer.html' %}
{% endblock content %}

templates/search.html
{% load static %}

{% block content %}
    {% block search %}
        <div class="col-8">
            <div class="search-div">
                <form action="{% url 'products:search' %}" method="get">
                    <div class="input-group input-group-lg mb-3">
                        <input class="search-input form-control secondary-search" type="text" placeholder="Produit" aria-label="Search" name="product_search">
                        <div class="input-group-append">
                            <button class="btn btn-primary btn-xl js-scroll-trigger search-btn" type="submit">Chercher</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    {% endblock search %}
{% endblock content %}